name: Build and Release

on:
    push:
        tags:
            - "*.*.*.*"

jobs:
    Build:
        runs-on: ubuntu-latest
        env:
            DALAMUD_HOME: /tmp/dalamud
            DALAMUD_ARCHIVE_URL: ${{ vars.DALAMUD_ARCHIVE_URL || 'https://goatcorp.github.io/dalamud-distrib/latest.zip' }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Set up .NET
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: 9.0.x

            - name: Download Dalamud Latest
              run: |
                  wget ${{ env.DALAMUD_ARCHIVE_URL }} -O ${{ env.DALAMUD_HOME }}.zip
                  unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

            - name: Restore Project
              run: dotnet restore

            - name: Build Project
              run: dotnet build --configuration Release FFXIVQuotesClient/FFXIVQuotesClient.csproj -p:AssemblyVersion=${{ github.ref_name }}

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: ${{ github.ref_name }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload Release Archive
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: FFXIVQuotesClient/bin/Release/FFXIVQuotesClient/latest.zip
                  asset_name: FFXIVQuotesClient.zip
                  asset_content_type: application/zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
